DjangoApp/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from datetime import datetime
from django.conf.urls import patterns, url,include
from app.forms import BootstrapAuthenticationForm
from app.views import *
from app.models import *
from usermanagement.models import *
from django.contrib.auth.views import *
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    #url(r'^', include('app.urls', namespace="app")),
    url(r'^', include('usermanagement.urls', namespace="usermanagement")),
    url(r'^', include('atracker.urls', namespace="atracker")),
    url(r'^contact$', contact, name='contact'),
    url(r'^my$', myacc, name='myacc'),
    url(r'^about', about, name='about'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    ]

atracker/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from atracker.views import StudentsList, CreateStudentView, UpdateStudentView , CreateGroupReportView,\
    CreateStudentReports, DeleteGroupReport, PrefectsList, GroupsList, GroupInfo 

urlpatterns = patterns('',
     url(r'^students_list$', StudentsList.as_view(), name = 'stud_list'),
     url(r'^create_student$', CreateStudentView.as_view(), name = 'student-new'),
     url(r'^edit_student/(?P<pk>\d+)/$', UpdateStudentView.as_view(), name='student-edit',),
     url(r'^create_report$', CreateGroupReportView.as_view(), name = 'report-new'),
     url(r'^delete_report/(?P<pk>\d+)/$', DeleteGroupReport.as_view(), name='report-delete',),
     url(r'^create_student_reports/(?P<pk>\d+)/$', CreateStudentReports.as_view(), name = 'student-reports-edit'),
     url(r'^prefects_list$', PrefectsList.as_view(), name = 'prefects-list'),
     url(r'^groups_list$', GroupsList.as_view(), name = 'groups-list'),
     url(r'^group_info/(?P<pk>\d+)/$', GroupInfo.as_view(), name = 'group-info'),
    )

usermanagement/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from usermanagement.views import RegisterUser, LoginUser, UpdateProfileView,\
	UpdatePrefectInfo, CreateGroupView, CreatePrefectView
from django.contrib.auth.views import logout

# Uncomment the next lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test

# Where to redirect user if he is already logged in
login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), reverse_lazy('myacc'), redirect_field_name=None)

admin.autodiscover()

urlpatterns = patterns('',
	     url(r'^$', login_forbidden(LoginUser.as_view()), name='login'),
     url(r'^logout$', logout, {  'next_page': '/'  },        name='logout'),
     url(r'^register$', RegisterUser.as_view(), name = 'register'),
     url(r'^edit_profile/$', UpdateProfileView.as_view(), name = 'profile-edit'),
     url(r'^edit_prefect_profile/$', UpdatePrefectInfo.as_view(), name = 'prefect-edit'),
     url(r'^create_group/$', CreateGroupView.as_view(), name = 'group-create'),
     url(r'^add_prefect/$', CreatePrefectView.as_view(), name = 'prefect-create')

    )

attendancetracker/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Nure Cloud Services</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'content/site.css' %}" />
    <script src="{% static 'scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Nure Cloud Services</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li><a href="{% url 'usermanagement:profile-edit' %}">Мой профиль</a></li>
                {% endif %}
                <!--
                    <li><a href="{% url 'usermanagement:login' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                    -->
                </ul>
                {% include 'usermanagement/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Made in NURE </p>
        </footer>
    </div>

    <script src="{% static 'scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'scripts/bootstrap.js' %}"></script>
    <script src="{% static 'scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>