DjangoApp/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from datetime import datetime
from django.conf.urls import patterns, url,include
from app.forms import BootstrapAuthenticationForm
from app.views import *
from app.models import *
from usermanagement.models import *
from django.contrib.auth.views import *
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    #url(r'^', include('app.urls', namespace="app")),
    url(r'^', include('usermanagement.urls', namespace="usermanagement")),
    url(r'^', include('atracker.urls', namespace="atracker")),
    url(r'^contact$', contact, name='contact'),
    url(r'^my$', myacc, name='myacc'),
    url(r'^about', about, name='about'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    ]

atracker/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from atracker.views import StudentsList, CreateStudentView, UpdateStudentView , CreateGroupReportView,\
    CreateStudentReports, DeleteGroupReport, PrefectsList, GroupsList, GroupInfo 

urlpatterns = patterns('',
     url(r'^students_list$', StudentsList.as_view(), name = 'stud_list'),
     url(r'^create_student$', CreateStudentView.as_view(), name = 'student-new'),
     url(r'^edit_student/(?P<pk>\d+)/$', UpdateStudentView.as_view(), name='student-edit',),
     url(r'^create_report$', CreateGroupReportView.as_view(), name = 'report-new'),
     url(r'^delete_report/(?P<pk>\d+)/$', DeleteGroupReport.as_view(), name='report-delete',),
     url(r'^create_student_reports/(?P<pk>\d+)/$', CreateStudentReports.as_view(), name = 'student-reports-edit'),
     url(r'^prefects_list$', PrefectsList.as_view(), name = 'prefects-list'),
     url(r'^groups_list$', GroupsList.as_view(), name = 'groups-list'),
     url(r'^group_info/(?P<pk>\d+)/$', GroupInfo.as_view(), name = 'group-info'),
    )

usermanagement/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from usermanagement.views import RegisterUser, LoginUser, UpdateProfileView,\
	UpdatePrefectInfo, CreateGroupView, CreatePrefectView
from django.contrib.auth.views import logout

# Uncomment the next lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test

# Where to redirect user if he is already logged in
login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), reverse_lazy('myacc'), redirect_field_name=None)

admin.autodiscover()

urlpatterns = patterns('',
	     url(r'^$', login_forbidden(LoginUser.as_view()), name='login'),
     url(r'^logout$', logout, {  'next_page': '/'  },        name='logout'),
     url(r'^register$', RegisterUser.as_view(), name = 'register'),
     url(r'^edit_profile/$', UpdateProfileView.as_view(), name = 'profile-edit'),
     url(r'^edit_prefect_profile/$', UpdatePrefectInfo.as_view(), name = 'prefect-edit'),
     url(r'^create_group/$', CreateGroupView.as_view(), name = 'group-create'),
     url(r'^add_prefect/$', CreatePrefectView.as_view(), name = 'prefect-create')

    )

usermanagement/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from __future__ import unicode_literals
# Django libraries
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.encoding import smart_unicode
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from unittest.util import _MAX_LENGTH


# Custom User class that enhances the capabilities of the AbstracUser

CS = u'cs'
CE = u'cem'
NONE = u'none'
AI = u"ai"
ST = u"st"
ICS = u"ics"
MST = u"mst"
SE = u"se"
FACULTIES = (
	(CS, u"КН"),
	(CE, u"КИУ"),
	(NONE, u"Неизвестно")
	)
DEPARTMENTS = (
	(AI, u"ИИ"),
	(ST, u"СТ"),
	(ICS, u"ИУС"),
	(MST, u"МСТ"),
	(SE, u"ПИ"),
	(NONE, u"Неизвестно")
	)	
class CustomUser(AbstractUser):

	PREFECT = u'prefect'
	FACULTY_MEMBER = u'fmember'
	ADMIN = u'admin'
	UNDEF = u'undef'

	ACCOUNT_TYPE_CHOICES = (
		(PREFECT, u"Староста"),
		(FACULTY_MEMBER, u"Сотрудник деканата"),
		(ADMIN, u"Администратор"),
		(UNDEF, u"Неопределившийся")
		)
	middle_name = models.CharField(
		max_length = 100,
		blank = True,
		null = True,
		default = None
		)
	# Данные для подтверждения по почте
	activation_key = models.CharField(
		max_length=100,
		blank=True, 
		verbose_name = u'Ключ активации')

	key_expires = models.DateTimeField(
		default=timezone.now, 
		verbose_name = u'Срок действия ключа')

	# Account type: prefect, faculty member
	profile_type = models.CharField(
		max_length=50, 
		choices = ACCOUNT_TYPE_CHOICES, 
		default = UNDEF)
	
	approved = models.BooleanField(
		default = False,
		verbose_name = u"Личность подтверждена"
		)
	faculty = models.CharField(
		max_length = 200,
		choices = FACULTIES,
		default = CS,
		blank = True
		)
	
	department = models.CharField(
		max_length = 200,
		choices = DEPARTMENTS,
		blank = True,
		default = None
		)
	
	def __unicode__(self):
		return smart_unicode(self.get_full_name())

class Group(models.Model):
	
	group_name = models.CharField(
		max_length = 50, unique = True
		)
	
	faculty = models.CharField(
		max_length = 200,
		choices = FACULTIES,
		default = CS,
		blank = True
		)
	
	department = models.CharField(
		max_length = 200,
		choices = DEPARTMENTS,
		blank = True,
		default = None
		) 
	current_study_year = models.PositiveSmallIntegerField(
		validators=[MinValueValidator(1), MaxValueValidator(5)],
		verbose_name = "Курс", default = 3)
	def __unicode__(self):
		return self.group_name

# TODO: add the link to the last report and to group reports maybe 
class ResponsiblePerson(models.Model):
	user = models.OneToOneField(CustomUser, related_name = 'rp_profile')
	phone_number = models.CharField(max_length = 20, default = None, blank = True, null = True)
	status_confirmed = models.BooleanField(default = False)
	# group can have multiple responsible persons
	group = models.ForeignKey(Group, blank = True, null = True, default = None)

usermanagement/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import View
from usermanagement.forms import BootstrapRegistrationForm,BootstrapAuthenticationForm, ProfileForm, ResponsiblePersonForm, CreateGroupForm, CreateUserForm, CreateRPForm
from django.shortcuts import render_to_response, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.views.generic.edit import UpdateView
from django.views.generic import CreateView
from usermanagement.models import CustomUser, ResponsiblePerson, Group


"""
View to login and register the user 
Supports post and get requests
POST request:
    If the user has not been activated, throws and error that is displayed on the same page
    If the provided credentials are invalid, throws and error that is displayed on the same page
GET request:
    If the get request was made after the registration then:
        - pre-populate the username field so that the user can login right away
        - show successfull registration notifcator
    If this is a new get request:
        - show login form
        - show registration form
Database effects:
    None

TODO: enable email activation
"""

class LoginUser(View):

    def post(self, request, *args, **kwargs):
        form = BootstrapAuthenticationForm(data = request.POST)
        registration_form = BootstrapRegistrationForm()
        context_dict = {'form': form, 'registration_form': registration_form, 'title':u"Войти",}
        context = RequestContext(request)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('myacc'))
            else:
                context_dict['user_inactive'] = u'Вы не активировали ваш аккаунт!'
                return render_to_response(
                    'usermanagement/login.html', 
                    context_dict, 
                    context)
        else:
            return render_to_response(
                'usermanagement/login.html', 
                context_dict, 
                context)

    def get(self, request, *args, **kwargs):

        registration_form = BootstrapRegistrationForm()
        context_dict = {'registration_form': registration_form, 'title':u"Войти",}
        # check if this get request was sent after successull registration
        context_dict['registered'] = request.session.pop('registered', None)
        # if the registration failed then extract errors to pass them further
        context_dict['reg_errors'] = request.session.pop('reg_errors',None)
        if context_dict['registered']:
            reg_data = request.session['reg_data']
            # if the user was registred succesfully, prepopulate the form
            form = BootstrapAuthenticationForm(initial={'username': reg_data['username']})
        else:
            form = BootstrapAuthenticationForm()
        context_dict['form'] = form
        context = RequestContext(request)
        return render_to_response('usermanagement/login.html', context_dict, context)

"""
View to register the user
Supports post method only
POST:
    - register user if he provided valid registration data (i.e. email and two password samples)
    - if the registration failed pass messages to the login view

Database effects:
    - adds new entry to CustomUser table

TODO: implement email activation, uncomment save to database

"""
class RegisterUser(View):            
    registered = False #will be set to True if the registration completes successfully
    template_name = 'usermanagement/login.html'
    def post(self, request, *args, **kwargs):
        context = RequestContext(request)    
        form = BootstrapAuthenticationForm()
        registration_form = BootstrapRegistrationForm(request.POST)
        if registration_form.is_valid():
            user = registration_form.save()
            user.email = user.username
            user.save()

            #user.set_password(user.password)  
            user.is_active = True
            #salt = hashlib.sha1(str(random.random())).hexdigest()[:5]            
            #activation_key = hashlib.sha1(salt+user.email).hexdigest()            
            #key_expires = datetime.datetime.today() + datetime.timedelta(2)
            #user.activation_key = activation_key
            #user.key_expires = key_expires	
            #email_subject = u'Подтвердите регистрацию в Nure Cloud Services'
            #message = "Нажмите на ссылку, чтобы активировать свою учетную запись http://atracker.azurewebsites.net/confirm/%s" % (activation_key)	
            #send_mail(email_subject, message, 'noreply@atracker.azurewebsites.net', [user.email], fail_silently=False)
            user.save()
            request.session['registered'] = True
            request.session['reg_data'] = request.POST
            return HttpResponseRedirect(reverse('usermanagement:login'))
        else:
            request.session['registered'] = False
            request.session['reg_errors'] = registration_form.errors
            return HttpResponseRedirect(reverse('usermanagement:login'))


class UpdateProfileView(UpdateView):
    model = CustomUser
    form_class = ProfileForm
    template_name = 'usermanagement/user_profile.html'
    def form_valid(self, form):
        user = form.save(commit=False)
        if user.profile_type == u"prefect" and not hasattr(user, 'rp_profile'):
            rp_profile = ResponsiblePerson(user = self.request.user)
            rp_profile.save()
        return super(UpdateProfileView, self).form_valid(form)
    def get_success_url(self):
        nextl = self.request.GET.get('next', None)
        if nextl:
            return reverse(nextl)
        else:
            return reverse('myacc')
    def get_object(self):
        return self.request.user
    def get_context_data(self, **kwargs):
        nextl = self.request.GET.get('next', None)
        context = super(UpdateProfileView, self).get_context_data(**kwargs)
        context['action'] = reverse('usermanagement:profile-edit')
        if nextl:
            context["next"] = nextl
        return context

# TODO: check why the department is not saved
class UpdatePrefectInfo(UpdateView):
    model = ResponsiblePerson
    form_class = ResponsiblePersonForm 
    template_name = 'usermanagement/prefect_profile.html'
    def get_object(self):
        return self.request.user.rp_profile
    def get_context_data(self, **kwargs):
        context = super(UpdatePrefectInfo, self).get_context_data(**kwargs)
        context['action'] = reverse('usermanagement:prefect-edit')
        return context
    def get_success_url(self):
        return reverse('myacc')

class CreateGroupView(CreateView):
    model = Group 
    form_class = CreateGroupForm
    template_name = 'usermanagement/edit_group.html'
    def context_date(self, **kwargs):
        context = super(UpdatePrefectInfo, self).get_context_data(**kwargs)
        context['action'] = reverse('usermanagement:group-create')
        return context
    def get_success_url(self):
        if self.request.user.profile_type == u"prefect" and not hasattr(self.request.user, 'rp_profile'): 
            return reverse('usermanagement:prefect-edit')
        else:
            return reverse('usermanagement:prefect-create')
    
class CreatePrefectView(View):
    def get(self, request, *args, **kwargs):
        userForm = CreateUserForm
        rpForm = CreateRPForm
        context_dict = {}
        context_dict["userForm"] = userForm
        context_dict["rpForm"] = rpForm
        context = RequestContext(request)
        return render_to_response('usermanagement/add_prefect.html', context_dict, context)
    def post(self, request, *args, **kwargs):
        userForm = CreateUserForm(data = request.POST)
        rpForm = CreateRPForm(data = request.POST)
        if userForm.is_valid() and rpForm.is_valid():
            print(rpForm.cleaned_data['group'])
            user = userForm.save()
            user.username = user.email
            user.profile_type = u'prefect'
            user.set_password('0000')
            user.save()
            rp = ResponsiblePerson(
                user = user,
                group = rpForm.cleaned_data['group'],
                phone_number = rpForm.cleaned_data['phone_number']
                )
            rp.save()
            return HttpResponseRedirect(reverse('myacc'))
        else:
            context_dict = {}
            context_dict["userForm"] = userForm
            context_dict["rpForm"] = rpForm
            context = RequestContext(request)
            return render_to_response('usermanagement/add_prefect.html', context_dict, context)
            
    
        
    

usermanagement/templates/usermanagement/add_prefect.html
{% extends "layout.html" %}
{% block content %}

<h3>Добавить старосту</h3>
<p>Обязательные поля отмечены *. Они необходимы для создания корректной структуры отчетов.</p>
<p>По умолчанию адрес почты будет установлен в качестве логина, пароль - 0000</p>
<p>Если группы нет в списке, добавьте ее <a href="{% url 'usermanagement:group-create' %}"><b>ТУТ</b></a>. После добавления вы будете возвращены на эту страницу</p>
<form class = "form-horizontal" role="form" action="{% url 'usermanagement:prefect-create' %}" method="POST">
{% csrf_token %}
{{ userForm }}
{{ rpForm }}

	<br />
	<div class="btn-group" id="sbutton_wrapper">
		<button type="submit" class="btn btn-primary" id="save_blog" title="Сохранить">Сохранить</button>                  	
	</div>
</form>
{% endblock %}

usermanagement/templates/usermanagement/edit_group.html
{% extends "layout.html" %}

{% block content %}
 <form class = "form-horizontal" role="form" action="{{ action }}" method="POST">
	{% csrf_token %}
	{{ form }}
	<br />
	<div class="btn-group" id="sbutton_wrapper">
		<button type="submit" class="btn btn-primary" id="save_blog" title="Сохранить">Сохранить</button>                  	
	</div>
</form>
{% endblock %}

usermanagement/templates/usermanagement/full_edit.html
{% extends "layout.html" %}

{% block content %}

Некая хрень
{% endblock %}

usermanagement/templates/usermanagement/login.html
{% extends "layout.html" %}

{% block content %}


<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}               
                <h4>Войдите, чтобы воспользоваться сервисом:</h4>
                <hr />
                {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>Неверное имя пользователя/пароль.</strong>
                </div>
                {% endif %}
                
                
 
                <div class="form-group">
                    <!--  <label for="id_username" class="col-md-2 control-label">Логин</label>  -->
                    <div class="col-md-10">
                                     <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    {{ form.username }}
  </div>
                    
                    </div>
                </div>
                <div class="form-group">
                    <!--  <label for="id_password" class="col-md-2 control-label">Пароль</label> -->
                    <div class="col-md-10">
                    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
    {{ form.password }}
  </div>
                        
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

<!-- Registration form -->
{% if registered %}

        <div class="alert alert-success" role="alert">
       Пользователь успешно зарегистрирован
        </div>

{% else %}

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
        <!-- Change here -->
            <form action="{% url 'usermanagement:register' %}" method="post" class="form-horizontal">
                {% csrf_token %}               
                <h4>Или зарегистрируйтесь:</h4>
                <hr />
                <div class="form-group">
                    <!-- <label for="id_username" class="col-md-2 control-label">Адрес эл.почты</label> -->
                    <div class="col-md-10">
                    	<div class="input-group">
    						<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    		{{ registration_form.username }}
  						</div>
                    </div>
                </div>
                {% if reg_errors.username %}
                <div class="alert alert-danger">
                    <strong>Пользователь с таким адресом электронной почты уже существует</strong>
                </div>
                {% endif %}

                <div class="form-group">
                    <!--  <label for="id_password1" class="col-md-2 control-label">Пароль</label> -->
                    <div class="col-md-10">
                    	<div class="input-group">
    						<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    		{{ registration_form.password1 }}
  						</div>
                    </div>
                </div>
                <div class="form-group">
                    <!-- <label for="id_password2" class="col-md-2 control-label">Пароль (снова)</label> -->
                    <div class="col-md-10">
                        <div class="input-group">
    						<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    		{{ registration_form.password2 }}
  						</div>
                    </div>
                </div>
                {% if reg_errors.password2 %}
                <div class="alert alert-danger">
                    <strong>Пароли не совпадают</strong>
                </div>
                {% endif %}
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Зарегистрироваться" class="btn btn-default" />
                    </div>
                </div>
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>
{% endif %}


{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

usermanagement/templates/usermanagement/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет, {{ user.first_name }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>

</form>

{% endif %}

usermanagement/templates/usermanagement/prefect_profile.html
{% extends "layout.html" %}
{% block content %}
<div class="containter">
<h3>Информация об ответственном лице</h3>
<p>Для начала работы укажите, пожалуйста, группу и номер телефона.</p>
<form class="form-horizontal" role="form" action="{{ action }}" method="POST">
	{% csrf_token %}
	<div class="input-group">
    	<span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
    	{{ form.group }}
  	</div>
  	<div class="input-group">
  	<span class="input-group-addon"><i class="glyphicon glyphicon-phone"></i></span>
	{{ form.phone_number }}
	</div>
	 <br />
		<div class="btn-group" id="sbutton_wrapper">
		<button type="submit" class="btn btn-primary" id="save_student" title="Сохранить">Сохранить</button>                  
		</div>
</form><br/>
<p>Если вашей группы внезапно нет в списке, то вы можете добавить ее здесь (это недолго):</p>

<p><a href="{% url 'usermanagement:group-create' %}" class="btn btn-primary" role="button">Нажми меня</a></p>

</div>
{% endblock %}

usermanagement/templates/usermanagement/user_profile.html
{% extends "layout.html" %}

{% block content %}
<h3>Изменить профиль</h3>
<div class="container">
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Личные данные</a></li>
    <li><a data-toggle="tab" href="#menu1">Изменить пароль</a></li>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
       	<form role="form" action="{{ action }}{% if next %}?next={{ next }}{% endif %}" method="POST">
		{% csrf_token %}
	
			{{ form }}<br/>
			<div class="btn-group" id="sbutton_wrapper">
				<button type="submit" class="btn btn-primary" id="save_blog" title="Сохранить">Сохранить</button>
			</div>
		</form>
    </div>
    <div id="menu1" class="tab-pane fade">
      <p>Да-да, скоро тут можно будет менять пароль.</p>
    </div>
</div>
</div>
{% endblock %}