DjangoApp/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from datetime import datetime
from django.conf.urls import patterns, url,include
from app.forms import BootstrapAuthenticationForm
from app.views import *
from app.models import *
from usermanagement.models import *
from django.contrib.auth.views import *
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    #url(r'^', include('app.urls', namespace="app")),
    url(r'^', include('usermanagement.urls', namespace="usermanagement")),
    url(r'^', include('atracker.urls', namespace="atracker")),
    url(r'^contact$', contact, name='contact'),
    url(r'^my$', myacc, name='myacc'),
    url(r'^about', about, name='about'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    ]

atracker/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from atracker.views import StudentsList, CreateStudentView, UpdateStudentView , CreateGroupReportView,\
    CreateStudentReports, DeleteGroupReport, PrefectsList, GroupsList, GroupInfo 

urlpatterns = patterns('',
     url(r'^students_list$', StudentsList.as_view(), name = 'stud_list'),
     url(r'^create_student$', CreateStudentView.as_view(), name = 'student-new'),
     url(r'^edit_student/(?P<pk>\d+)/$', UpdateStudentView.as_view(), name='student-edit',),
     url(r'^create_report$', CreateGroupReportView.as_view(), name = 'report-new'),
     url(r'^delete_report/(?P<pk>\d+)/$', DeleteGroupReport.as_view(), name='report-delete',),
     url(r'^create_student_reports/(?P<pk>\d+)/$', CreateStudentReports.as_view(), name = 'student-reports-edit'),
     url(r'^prefects_list$', PrefectsList.as_view(), name = 'prefects-list'),
     url(r'^groups_list$', GroupsList.as_view(), name = 'groups-list'),
     url(r'^group_info/(?P<pk>\d+)/$', GroupInfo.as_view(), name = 'group-info'),
    )

usermanagement/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from usermanagement.views import RegisterUser, LoginUser, UpdateProfileView,\
	UpdatePrefectInfo, CreateGroupView, CreatePrefectView
from django.contrib.auth.views import logout

# Uncomment the next lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test

# Where to redirect user if he is already logged in
login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), reverse_lazy('myacc'), redirect_field_name=None)

admin.autodiscover()

urlpatterns = patterns('',
	     url(r'^$', login_forbidden(LoginUser.as_view()), name='login'),
     url(r'^logout$', logout, {  'next_page': '/'  },        name='logout'),
     url(r'^register$', RegisterUser.as_view(), name = 'register'),
     url(r'^edit_profile/$', UpdateProfileView.as_view(), name = 'profile-edit'),
     url(r'^edit_prefect_profile/$', UpdatePrefectInfo.as_view(), name = 'prefect-edit'),
     url(r'^create_group/$', CreateGroupView.as_view(), name = 'group-create'),
     url(r'^add_prefect/$', CreatePrefectView.as_view(), name = 'prefect-create')

    )

usermanagement/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from __future__ import unicode_literals
# Django libraries
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.encoding import smart_unicode
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from unittest.util import _MAX_LENGTH


# Custom User class that enhances the capabilities of the AbstracUser

CS = u'cs'
CE = u'cem'
NONE = u'none'
AI = u"ai"
ST = u"st"
ICS = u"ics"
MST = u"mst"
SE = u"se"
FACULTIES = (
	(CS, u"КН"),
	(CE, u"КИУ"),
	(NONE, u"Неизвестно")
	)
DEPARTMENTS = (
	(AI, u"ИИ"),
	(ST, u"СТ"),
	(ICS, u"ИУС"),
	(MST, u"МСТ"),
	(SE, u"ПИ"),
	(NONE, u"Неизвестно")
	)	
class CustomUser(AbstractUser):

	PREFECT = u'prefect'
	FACULTY_MEMBER = u'fmember'
	ADMIN = u'admin'
	UNDEF = u'undef'

	ACCOUNT_TYPE_CHOICES = (
		(PREFECT, u"Староста"),
		(FACULTY_MEMBER, u"Сотрудник деканата"),
		(ADMIN, u"Администратор"),
		(UNDEF, u"Неопределившийся")
		)
	middle_name = models.CharField(
		max_length = 100,
		blank = True,
		null = True,
		default = None
		)
	# Данные для подтверждения по почте
	activation_key = models.CharField(
		max_length=100,
		blank=True, 
		verbose_name = u'Ключ активации')

	key_expires = models.DateTimeField(
		default=timezone.now, 
		verbose_name = u'Срок действия ключа')

	# Account type: prefect, faculty member
	profile_type = models.CharField(
		max_length=50, 
		choices = ACCOUNT_TYPE_CHOICES, 
		default = UNDEF)
	
	approved = models.BooleanField(
		default = False,
		verbose_name = u"Личность подтверждена"
		)
	faculty = models.CharField(
		max_length = 200,
		choices = FACULTIES,
		default = CS,
		blank = True
		)
	
	department = models.CharField(
		max_length = 200,
		choices = DEPARTMENTS,
		blank = True,
		default = None
		)
	
	def __unicode__(self):
		return smart_unicode(self.get_full_name())

class Group(models.Model):
	
	group_name = models.CharField(
		max_length = 50, unique = True
		)
	
	faculty = models.CharField(
		max_length = 200,
		choices = FACULTIES,
		default = CS,
		blank = True
		)
	
	department = models.CharField(
		max_length = 200,
		choices = DEPARTMENTS,
		blank = True,
		default = None
		) 
	current_study_year = models.PositiveSmallIntegerField(
		validators=[MinValueValidator(1), MaxValueValidator(5)],
		verbose_name = "Курс", default = 3)
	def __unicode__(self):
		return self.group_name

# TODO: add the link to the last report and to group reports maybe 
class ResponsiblePerson(models.Model):
	user = models.OneToOneField(CustomUser, related_name = 'rp_profile')
	phone_number = models.CharField(max_length = 20, default = None, blank = True, null = True)
	status_confirmed = models.BooleanField(default = False)
	# group can have multiple responsible persons
	group = models.ForeignKey(Group, blank = True, null = True, default = None)

atracker/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of views.
"""

# Стандартные библиотеки
from __future__ import unicode_literals
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from atracker.models import Student, GroupReport, StudentReport
from atracker.forms import CreateStudentForm, CreateGroupReportForm, StudentReportFormSet
from django.db.models import Q
from datetime import date
from django.http import HttpResponseRedirect
# Create your views here.
from django.template.defaulttags import register
from usermanagement.models import ResponsiblePerson, Group

@register.filter(name='lookup')
def cut(value, arg):
    return value[arg]

class StudentsList(View):
    template_name = 'stud_list.html'
    @method_decorator(login_required)  
    def get(self, request, *args, **kwargs):
        user = request.user
        context_dict = {}
        if user.rp_profile:
            rp_profile = user.rp_profile
            context_dict["status"] = "OK"
            context_dict["group"] = rp_profile.group
            students = Student.objects.filter(group = rp_profile.group)
            context_dict["students"] = students
        else:
            context_dict["status"] = "Reject"
        context = RequestContext(request)                 
        return render_to_response(
            self.template_name,
            context_dict, context)
        
class CreateStudentView(CreateView):
    model = Student
    form_class = CreateStudentForm
    template_name = 'edit_student.html'
    
    def form_valid(self, form):
        student = form.save(commit=False)
        student.group = self.request.user.rp_profile.group
        #if not student.year_of_birth is None and not student.month_of_birth is None and not student.day_of_birth is None:
        #    student.date_of_birth = date(student.year_of_birth, student.month_of_birth, student.day_of_birth)
        print(student.date_of_birth)
        return super(CreateStudentView, self).form_valid(form)
    def get_success_url(self):
        return reverse('atracker:stud_list')

    def get_context_data(self, **kwargs):

        context = super(CreateStudentView, self).get_context_data(**kwargs)
        context['action'] = reverse('atracker:student-new')

        return context

class UpdateStudentView(UpdateView):
    model = Student
    form_class = CreateStudentForm
    template_name = 'edit_student.html'
    def form_valid(self, form):
        student = form.save(commit=False)
        #if not student.year_of_birth is None and not student.month_of_birth is None and not student.day_of_birth is None:
        #    student.date_of_birth = date(student.year_of_birth, student.month_of_birth, student.day_of_birth)
        #else:
        #    student.date_of_birth = None
        return super(UpdateStudentView, self).form_valid(form)
    def get_success_url(self):
        return reverse('atracker:stud_list')

    def get_context_data(self, **kwargs):

        context = super(UpdateStudentView, self).get_context_data(**kwargs)
        context['action'] = reverse('atracker:student-edit', kwargs={'pk': self.get_object().id})

        return context
    
class CreateGroupReportView(CreateView):
    model = GroupReport
    form_class = CreateGroupReportForm
    template_name = 'add_report.html'
    repid = None
    def form_valid(self, form):
        group = self.request.user.rp_profile.group
        report = form.save(commit=False)
        report.group = group
        report.responsible_person = self.request.user
        response = super(CreateGroupReportView, self).form_valid(form)
        students = Student.objects.filter(group = group)
        for student in students:
            student_report = StudentReport(report = report, student = student, comments="")
            student_report.save()
        return response
    
    def get_success_url(self):
        return reverse("atracker:student-reports-edit", kwargs={'pk': self.object.id})
    
    def get_context_data(self, **kwargs):
        context = super(CreateGroupReportView, self).get_context_data(**kwargs)
        context['action'] = reverse('atracker:report-new')
        return context

class CreateStudentReports(View):
    template_name = 'fill_in_reports.html'
    def get(self, request, *args, **kwargs):
        group = request.user.rp_profile.group
        students = Student.objects.filter(group = group)
        report_id = kwargs.get("pk")
        reports = StudentReport.objects.filter(report = report_id)
        formset =  StudentReportFormSet(queryset = reports)
        context_dict = {}
        context_dict["formset"] = formset
        context_dict["students"] = { x.id: x for x in students }
        context_dict["report"] = GroupReport.objects.get(id = report_id)
        return render(request, self.template_name,context_dict)
    
    def post(self, request, *args, **kwargs):
        #group = request.user.rp_profile.group
        formset =  StudentReportFormSet(request.POST)
        formset.save()
        return HttpResponseRedirect(reverse('myacc'))

class DeleteGroupReport(DeleteView):
    model = GroupReport
    template_name = 'atracker/delete_report.html'
    
    def get_success_ulr(self):
        return reverse('myacc') 
            
class PrefectsList(View):
    template_name = 'pref_list.html'
    def get(self, request, *args, **kwargs):
        context_dict = {}
        if request.user.profile_type == "fmember" and (request.user.faculty == "" or request.user.faculty == u"none"):
            context_dict["next"] = 'atracker:prefects-list'
            context_dict["no_faculty"] = True
        else:
            fac = request.user.faculty
            context_dict["no_faculty"] = False
            rpeople = ResponsiblePerson.objects.filter(user__faculty = fac)
            context_dict["rpeople"] = rpeople
            """
            no_fac_people = ResponsiblePerson.objects.filter(Q(user__faculty = u"") | 
                                                             Q(user__faculty = u"none") | 
                                                             Q(user__faculty = None))
            #no_fac_people = ResponsiblePerson.objects.all()
            
            context_dict["no_fac_people"] = no_fac_people
            """ 
        return render(request, self.template_name,context_dict)

class GroupsList(View):
    template_name = 'groups_list.html'
    def get(self, request, *args, **kwargs):
        context_dict = {}
        if request.user.profile_type == "fmember" and (request.user.faculty == "" or request.user.faculty == u"none"):
            context_dict["next"] = 'atracker:prefects-list'
            context_dict["no_faculty"] = True
        else:
            fac = request.user.faculty
            context_dict["no_faculty"] = False
            students = Student.objects.filter(group__faculty = fac)
            context_dict["students"] = students
        return render(request, self.template_name,context_dict)

class GroupInfo(View):
    template_name = 'group_info.html'
    def get(self, request, *args, **kwargs):
        context_dict = {}  
        group_id = kwargs.get("pk")
        group = Group.objects.get(id = group_id)
        students = Student.objects.filter(group = group)
        context_dict['students'] = students
        context_dict["group"] = group
        return render(request, self.template_name,context_dict) 

atracker/templates/add_report.html
{% extends "layout.html" %}

{% block content %}
	{% if report.id %}	
	<div class="panel-heading"><h4>Изменить отчет</h4></div>	
	{% else %}
	<div class="panel-heading"><h4>Добавить отчет</h4></div>
	{% endif %}
	<form role="form" action="{{ action }}" method="POST">
	{% csrf_token %}
		{{ form }}<br/>
		<div class="btn-group" id="sbutton_wrapper">
		<button type="submit" class="btn btn-primary" id="save_report" title="Сохранить">Сохранить</button>                  
		</div>
		</form><br/>`
{% endblock %}

atracker/templates/edit_student.html
{% extends "layout.html" %}

{% block content %}
	{% if student.id %}	
	<div class="panel-heading"><h4>Изменить данные</h4></div>	
	{% else %}
	<div class="panel-heading"><h4>Добавить студента</h4></div>
	{% endif %}
	<form class="form-horizontal" role="form" action="{{ action }}" method="POST">
	{% csrf_token %}
	
  	{{ form }}
      	<br />
		<div class="btn-group" id="sbutton_wrapper">
		<button type="submit" class="btn btn-primary" id="save_student" title="Сохранить">Сохранить</button>                  
		</div>
		</form><br/>`
	
{% endblock %}

atracker/templates/fill_in_reports.html
{% extends "layout.html" %}

{% block content %}

<div class="table-responsive">
<form class="form-inline" method="post" action="">
		{% csrf_token %}
		<!-- One form to rule them all -->
	 		{{ formset.management_form }}
	 	{{ formset.non_form_errors.as_ul }}
	 	<div>
	 	<table id="formset" class="table table-condensed">
	 	<caption><h3>Журнал посещаемости за {{ report.month }}-{{ report.year }}</h3></caption>
		{% for form in formset %}
	 		{% if forloop.first %}
	 		<thead>
	 			<tr>
	 				<th> # </th>
	 				<th> Студент </th>
    				{% for field in form.visible_fields %}
    				<th>{{ field.label|capfirst }}</th>
    				{% endfor %}    			
  				</tr>
		  	</thead>
  			{% endif %}
  			<tbody>
  			<tr class="{% cycle row1,row2 %}">
  				{% for hidden in form.hidden_fields %}
      				{{ hidden }}
      			{% endfor %}
				
					{% with student=students|lookup:form.student.value %}
					<td>
						{{ student.journal_id }}
					</td>
					<td> 
						{{ student }}
					</td>  
					{% endwith %}
				
  				{% for field in form.visible_fields %}
    			<td>
      				{{ field.errors.as_ul }}
      				{{ field }}
    			</td>
  				{% endfor %}
  			</tr>
  			</tbody>
		{% endfor %}    
		</table>
		</div>
		<div class="btn-group" id="sbutton_wrapper">
			<button type="submit" class="btn btn-primary" id="save_report" title="Сохранить">Сохранить</button>                  
		</div>
</form>
</div>
{% endblock %}

atracker/templates/group_info.html
{% extends "layout.html" %}
{% block content %}
<h3>{{ group }}</h3>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th >#</th>
        <th>ФИО</th>
        <th>День рождения</th>
        <th>Статус</th>
      </tr>
    </thead>
    <tbody>
    {% for student in students %}
       <tr>
        <td>{% if student.journal_id %} {{ student.journal_id }} {% endif %}</td>
        <td>{{ student.last_name }}, {{ student.first_name }} {% if student.middle_name %} {{ student.middle_name }} {% endif %}</td>
        <td>{% if student.date_of_birth %} {{ student.date_of_birth }} {% else %} Не указано {% endif %}</td>
        <td>{% if student.requires_attention %} <span class="glyphicon glyphicon-exclamation-sign" style='color:red'"></span> {% else %} <span class="glyphicon glyphicon-ok" style='color:green'"></span> {% endif %}</td>
        
        
       </tr>
{% empty %}
      <tr>
      <td colspan="7">В списке пока нет студентов.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

atracker/templates/groups_list.html
{% extends "layout.html" %}
{% block content %}

{% if no_faculty %}
<h3>Ой...</h3>
<p>Что-то пошло не так - вы забыли указать факультет, без этого ничего не выйдет<p>
<p><a href="{% url 'usermanagement:profile-edit' %}{% if next %}?next={{ next }}{% endif %}" class="btn btn-info" role="button">Нажми меня</a></p>

{% else %}

<h3>Списки групп</h3>
<!--  mad grouping things going on -->
{% regroup students by group.get_department_display as depts %}
{% for dep in depts %}
<a href="#d{{ forloop.counter  }}" data-toggle="collapse"><button type="button" class="btn btn-lg btn-default btn-block">{{ dep.grouper }}</button></a>
<div id ="d{{ forloop.counter }}" class="collapse well">
 {% regroup dep.list by group.current_study_year as course_list %}
    {% for course in course_list %}
     <a href="#c{{ forloop.counter  }}{{ dep.grouper }}" data-toggle="collapse"><button type="button" class="btn btn-lg btn-default btn-block">{{ course.grouper }} курс</button></a>
    	<div id ="c{{ forloop.counter }}{{ dep.grouper }}" class="collapse well">
    	{% regroup course.list by group as group_list %} 
    	{% for group in group_list %}
    		<p>{{ group.grouper }} - <a href = "{% url 'atracker:group-info' group.grouper.id %}">полная информация о группе</a></p>
    	{% endfor %}
    	</div>
    	
    	{% endfor %}

</div>
{% endfor %}


{% endif %}
{% endblock %}

atracker/templates/pref_list.html
{% extends "layout.html" %}
{% block content %}

{% if no_faculty %}
<h3>Ой...</h3>
<p>Что-то пошло не так - вы забыли указать факультет, без этого ничего не выйдет<p>
<p><a href="{% url 'usermanagement:profile-edit' %}{% if next %}?next={{ next }}{% endif %}" class="btn btn-info" role="button">Нажми меня</a></p>

{% else %}
<!--  complicated grouping stuff -->
<br />

<div class="alert alert-warning">
Кнопка "ПНУТЬ" пока находится в стадии разработки, поэтому нажимать на нее бессмысленно, хотя и, безусловно, приятно.
</div>
{% regroup rpeople by user.get_department_display as depts %}
<ul class="nav nav-pills nav-justified">
	{% for dep in depts %}
	{% if forloop.first %}
    <li class="active"><a data-toggle="pill" href="#d{{ forloop.counter  }}">{{ dep.grouper }}</a></li>
    {% else %}
    <li><a data-toggle="pill" href="#d{{ forloop.counter  }}">{{ dep.grouper }}</a></li>
    {% endif %}
    {% endfor %}
</ul>



<div class="tab-content">
	<!--  group by department and then for each department -->
	{% regroup rpeople by user.get_department_display as depts %}
	{% for dep in depts %}
		{% if forloop.first %}
		<div id="d{{ forloop.counter }}" class="tab-pane fade in active">
		{% else %}
		<div id="d{{ forloop.counter }}" class="tab-pane fade">
		{% endif %}
		<!--  group by year of study and then for each year of study -->
    	{% regroup dep.list by group.current_study_year as course_list %}
    	<br/>
		<ul class="nav nav-tabs">
		{% for course in course_list %}
			{% if forloop.first %}
    		<li class="active"><a data-toggle="tab" href="#c{{ forloop.counter  }}">{{ course.grouper }} курс</a></li>
    		{% else %}
    		<li><a data-toggle="tab" href="#c{{ forloop.counter  }}">{{ course.grouper }} курс</a></li>
    		{% endif %}
    	{% endfor %}
		</ul>
		<br />
		<div class="tab-content">
		{% regroup dep.list by group.current_study_year as course_list %}
    	{% for course in course_list %}
    			{% if forloop.first %}
		<div id="c{{ forloop.counter }}" class="tab-pane fade in active">
		{% else %}
		<div id="c{{ forloop.counter }}" class="tab-pane fade">
		{% endif %}
    	<!-- group by study group and then for each group -->
    		{% regroup course.list by group as group_list %} 
    		{% for group in group_list %}
    		<div class="panel panel-default">
  				<div class="panel-heading"> <h4>{{ group.grouper }} </h4></div>
  				<div class="panel-body">
        		<p><a href = "{% url 'atracker:group-info' group.grouper.id %}">Список студентов</a></p>
        		<!--  for each prefect in group -->
        		{% for rp in group.list %}
        		<p>Староста: {{ rp.user }}</p>
        		<a href="#u{{ rp.user.id }}"  data-toggle="collapse"><button class="btn-primary btn-xs">Показать >></button></a>
        		<button class="btn-primary btn-xs" >ПНУТЬ!</button>
  				<div id="u{{ rp.user.id }}" class="collapse">
    				<table class="table table-striped table-bordered table-hover">
  						<tr>
    						<th>ФИО:</th>
    						<td>{{ rp.user }}</td>
  						</tr>
  						<tr>
    						<th>Почта:</th>
    						<td>{{ rp.user.email }}</td>
  						</tr>
  						<tr>
    						<th>Телефон:</th>
    						<td>{{ rp.user.rp_profile.phone_number }}</td>
  						</tr>
  						<tr>
  							<th>Последний раз был(а) в сети</th>
  							<td>{{ rp.user.last_login }}</td>
  						</tr>
					</table>
  				</div> <!--  close prefect info table div -->
        	{% endfor %} <!--  end of prefect loop -->
        	</div>
        </div>
    	{% endfor %} <!-- end of group loop -->
	</div> <!--  close year of study div -->
    {% endfor %} <!-- end of year of study loop -->
    </div> <!-- close year of study tab pane -->
    </div> <!-- closes department div -->   	
{% endfor %} <!-- end of department loop -->
</div>
{% endif %}
{% endblock %}

atracker/templates/stud_list.html
{% extends "layout.html" %}

{% block content %}

<h2>Список студентов</h2>
<p>
<a href="{% url 'atracker:student-new' %}"><button class="btn btn-primary" id="submit" title="Добавить студента">Добавить студента</button></a>
</p>
<p><b>#</b> - номер в журнале</p>
<p><b>Статус</b> - зеленая галочка значит, что студент не отчислен </p>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th >#</th>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Бездник</th>
        <th class="text-center" data-toggle="tooltip" title="Является студентом">Статус</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for student in students %}
      <tr>
        <td>{% if student.journal_id %} {{ student.journal_id }} {% endif %}</td>
        <td>{{ student.last_name }}</td>
        <td>{{ student.first_name }}</td>
        <td>{{ student.middle_name }}</td>
        <td>{% if student.date_of_birth %} {{ student.date_of_birth }} {% else %} Не указано {% endif %}</td>
        <td class="text-center">{% if student.active %}<span class="glyphicon glyphicon-ok" style='color:green'"></span>{% else %} Отчислен {% endif %}</td>
        <td class="text-center"><a href="{% url 'atracker:student-edit' pk=student.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
      </tr>
      {% empty %}
      <tr>
      <td colspan="7">Вы еще не добавили ни одного студента.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}