DjangoApp/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from datetime import datetime
from django.conf.urls import patterns, url,include
from app.forms import BootstrapAuthenticationForm
from app.views import *
from app.models import *
from usermanagement.models import *
from django.contrib.auth.views import *
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    #url(r'^', include('app.urls', namespace="app")),
    url(r'^', include('usermanagement.urls', namespace="usermanagement")),
    url(r'^', include('atracker.urls', namespace="atracker")),
    url(r'^contact$', contact, name='contact'),
    url(r'^my$', myacc, name='myacc'),
    url(r'^about', about, name='about'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    ]

atracker/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from atracker.views import StudentsList, CreateStudentView, UpdateStudentView , CreateGroupReportView,\
    CreateStudentReports, DeleteGroupReport, PrefectsList, GroupsList, GroupInfo 

urlpatterns = patterns('',
     url(r'^students_list$', StudentsList.as_view(), name = 'stud_list'),
     url(r'^create_student$', CreateStudentView.as_view(), name = 'student-new'),
     url(r'^edit_student/(?P<pk>\d+)/$', UpdateStudentView.as_view(), name='student-edit',),
     url(r'^create_report$', CreateGroupReportView.as_view(), name = 'report-new'),
     url(r'^delete_report/(?P<pk>\d+)/$', DeleteGroupReport.as_view(), name='report-delete',),
     url(r'^create_student_reports/(?P<pk>\d+)/$', CreateStudentReports.as_view(), name = 'student-reports-edit'),
     url(r'^prefects_list$', PrefectsList.as_view(), name = 'prefects-list'),
     url(r'^groups_list$', GroupsList.as_view(), name = 'groups-list'),
     url(r'^group_info/(?P<pk>\d+)/$', GroupInfo.as_view(), name = 'group-info'),
    )

usermanagement/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Definition of urls for DjangoApp.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from usermanagement.views import RegisterUser, LoginUser, UpdateProfileView,\
	UpdatePrefectInfo, CreateGroupView, CreatePrefectView
from django.contrib.auth.views import logout

# Uncomment the next lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test

# Where to redirect user if he is already logged in
login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), reverse_lazy('myacc'), redirect_field_name=None)

admin.autodiscover()

urlpatterns = patterns('',
	     url(r'^$', login_forbidden(LoginUser.as_view()), name='login'),
     url(r'^logout$', logout, {  'next_page': '/'  },        name='logout'),
     url(r'^register$', RegisterUser.as_view(), name = 'register'),
     url(r'^edit_profile/$', UpdateProfileView.as_view(), name = 'profile-edit'),
     url(r'^edit_prefect_profile/$', UpdatePrefectInfo.as_view(), name = 'prefect-edit'),
     url(r'^create_group/$', CreateGroupView.as_view(), name = 'group-create'),
     url(r'^add_prefect/$', CreatePrefectView.as_view(), name = 'prefect-create')

    )

app/templates/app/about.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/contact.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/dean_account.html
{% extends "layout.html" %}
{% block content %}
<h2>{{ title }}</h2>

<div>
<div class="panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">Списки</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <ul class="list-group">
        <a href="{% url 'atracker:prefects-list' %}"><li class="list-group-item">Личные карточки старост</li></a>
        <a href="{% url 'atracker:groups-list' %}"><li class="list-group-item">Списки групп</li></a>
        <a href="{% url 'usermanagement:prefect-create' %}"><li class="list-group-item">Добавить старосту</li></a>
      </ul>
    </div>
</div>
</div>
<div>
<div class="panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse2">Отчеты</a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <ul class="list-group">
        <li class="list-group-item">Новые отчеты (добавить циферку)</li>
        <li class="list-group-item">Архив</li>
      </ul>
    </div>
</div>
</div>

<div>
<div class="panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a href="#">Проблемы</a>
      </h4>
    </div>
</div>
</div>

<div>
<div class="panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a href="#">Волшебный пинок</a>
      </h4>
    </div>
</div>
</div>
{% endblock %}

app/templates/app/index.html
{% extends "layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.python.org/pypi">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Python Tools for Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/myacc.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}</h2>

{% if user.profile_type == "undef" %}
<div class="alert alert-warning">
Чтобы воспользоваться сервисом, заполните, пожалуйста, свой профиль.
</div>
<p><a href="{% url 'usermanagement:profile-edit' %}" class="btn btn-info" role="button">Заполнить профиль</a></p>

{% endif %}
<!--  here we must put the list of services, available to user -->
{% if user.profile_type == "fmember" %}

фырфырфыр
{% endif %}

{% if user.profile_type == "prefect" %}
	{% if user.rp_profile %}
	<p><a href="{% url 'atracker:stud_list' %}" class="btn btn-info" role="button">Список студентов</a> </p>

<p><a href="{% url 'atracker:report-new' %}" class="btn btn-info" role="button">Новый отчет</a></p>
<h3>Последние отчеты ({{ user.rp_profile.group }})</h3>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Месяц</th>
        <th>Год</th>
        <th>Заполнено</th>
        <th>Дата создания</th>
        <th>Отредактировано</th>
        <th>Просмотрено</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for report in reports %}
      <tr>
        <td>{{ report.month }}</td>
        <td>{{ report.year }}</td>
        <td>{{ report.responsible_person }}</td>
        <td>{{ report.timestamp|date:"D d M Y" }}</td>
        <td>{{ report.edited|date:"D d M Y" }}</td>
        <td class="text-center">{% if report.seen %} 
        	<span class="glyphicon glyphicon-eye-open" style="color:#B80000;"></span> 
        	{% else %}
        	<span class="glyphicon glyphicon-eye-close" style="color:gray;"></span> 
        	{% endif %}
        </td>
        <td class="text-center">
        {% if report.seen %}
        	<span class="glyphicon glyphicon-pencil" style="color:gray;></span></td>
        	<span class="glyphicon glyphicon-remove" style="color:gray;"></span></td>
        {% else %}
        <a href="{% url 'atracker:student-reports-edit' pk=report.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        <td><a data-toggle="modal" data-target="#myModal" href="#"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></a></td>
		<!-- Modal -->
                        <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog">

                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                  <h4 class="modal-title">Удаление отчета</h4>
                              </div>
                              <div class="modal-body">
                                  <p> {{ user.first_name }}, а вы уверены, что хотите удалить этот отчет?</p>
                              </div>
                              <div class="modal-footer">
                                 <div class="execute_block">
                                    <form action="{% url 'atracker:report-delete' pk=report.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary" id="save_blog" title="Удалить">Да, точно!</button>    
                                    </form>
                                </div>
                                <div class="go_back_block">
                                    <button class="btn btn-default" title="Передумал" data-dismiss="modal">Нет, вернуться!</button>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
                {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>



{% else %}
Подать заяку на статус ответственного лица.
{% endif %}
{% endif %}


{% endblock %}

app/templates/app/prefect_account.html
{% extends "layout.html" %}
{% block content %}
<h2>{{ title }}</h2>
{% if user.rp_profile.group %}
	<p><a href="{% url 'atracker:stud_list' %}" class="btn btn-info" role="button">Список студентов</a> </p>

<p><a href="{% url 'atracker:report-new' %}" class="btn btn-info" role="button">Новый отчет</a></p>
<h3>Последние отчеты ({{ user.rp_profile.group }})</h3>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Месяц</th>
        <th>Год</th>
        <th>Заполнено</th>
        <th>Дата создания</th>
        <th>Отредактировано</th>
        <th class="text-center">Просмотрено</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for report in reports %}
      <tr>
        <td>{{ report.month }}</td>
        <td>{{ report.year }}</td>
        <td>{{ report.responsible_person }}</td>
        <td>{{ report.timestamp|date:"D d M Y" }}</td>
        <td>{{ report.edited|date:"D d M Y" }}</td>
        <td class="text-center">{% if report.seen %} 
        	<span data-toggle="tooltip" title="Декан уже видел отчет" class="glyphicon glyphicon-eye-open" style="color:#B80000;"></span> 
        	{% else %}
        	<span data-toggle="tooltip" title="Отчет еще не просмотрен" class="glyphicon glyphicon-eye-close" style="color:gray;"></span> 
        	{% endif %}
        </td>
        <td>
        {% if report.seen %}
        	<span class="glyphicon glyphicon-pencil" style="color:gray;></span></td>
        	<span class="glyphicon glyphicon-remove" style="color:gray;"></span></td>
        {% else %}
        <a href="{% url 'atracker:student-reports-edit' pk=report.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        <td><a data-toggle="modal" data-target="#myModal" href="#"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></a></td>
		<!-- Modal -->
                        <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog">

                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                  <h4 class="modal-title">Удаление отчета</h4>
                              </div>
                              <div class="modal-body">
                                  <p> {{ user.first_name }}, а вы уверены, что хотите удалить этот отчет?</p>
                              </div>
                              <div class="modal-footer">
                                 <div class="execute_block">
                                    <form action="{% url 'atracker:report-delete' pk=report.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary" id="save_blog" title="Удалить">Да, точно!</button>    
                                    </form>
                                </div>
                                <div class="go_back_block">
                                    <button class="btn btn-default" title="Передумал" data-dismiss="modal">Нет, вернуться!</button>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
                {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>



{% else %}
Заполните, пожалуйста, данные профиля: укажите группу и номер телефона
<p><a href="{% url 'atracker:stud_list' %}" class="btn btn-info" role="button">Список студентов</a> </p>
{% endif %}

{% endblock %}